name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python>=3
  - numpy
  - jupyterlab
  - pip
  - python-graphviz
  - graphviz
  - pip:
    - pandas
    - matplotlib
    - sklearn
    - seaborn
    - graphviz
